export const NodeTitles = {
  'generic::node': 'Node',
  'generic::value': 'Value',
  'generic::math': 'Math',
  'generic::booleanmath': 'Boolean Math',
  'math::add': 'Add',
  'math::subtract': 'Subtract',
  'math::multiply': 'Multiply',
  'math::divide': 'Divide',
  'value::number': 'Number',
  'value::string': 'String',
  'value::object': 'Object',
  'value::boolean': 'Boolean',
  'booleanmath::and': 'And Gate',
  'booleanmath::or': 'Or Gate',
  'booleanmath::nand': 'Not And Gate',
  'booleanmath::nor': 'Not Or Gate',
  'booleanmath::xor': 'Exclusive Or Gate',
  'booleanmath::xnor': 'Exclusive Not Or Gate',
  'booleanmath::not': 'Not Gate',
  'string::length': 'String Length',
  'string::slice': 'Slice',
  'string::replace': 'Replace',
  'string::join': 'Join',
  'string::append': 'Append',
  'string::prepend': 'Prepend',
  'string::delete': 'Delete',
  'string::deleteat': 'Delete At',
  'runtime::output': 'Output',
  'runtime::log': 'Log To Console',
  'logic::currentindex': 'Current Index',
  'logic::forloop': 'For Loop',
  'logic::branch': 'Branch',
  'logic::compare': 'Compare',
  'object::property::create': 'Create Property',
  'object::property::get': 'Get Property',
  'object::property::set': 'Set Property',
  'object::property::value': 'Property Value',
  'object::property::delete': 'Delete property',
  'object::merge': 'Merge Objects',
} as const;
